nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161LogisticRegressionForLK > ~/log/20170502yfq20161LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161NaiveBayesForLK > ~/log/20170502yfq20161NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161DecisionTreeRegressionForLK > ~/log/20170502yfq20161DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161GradientBoostingRegressionForLK341 3 4 > ~/log/20170502yfq20161GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161GradientBoostingRegressionForLK66 6 6 > ~/log/20170502yfq20161GradientBoostingRegressionForLK66.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161GradientBoostingRegressionForLK106 10 6 > ~/log/20170502yfq20161GradientBoostingRegressionForLK106.log   &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161GradientBoostingRegressionForLK941 9 4 > ~/log/20170502yfq20161GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2016_train_variable 20170502yfq20161RandomForestRegressionForLK6 > ~/log/20170502yfq20161RandomForestRegressionForLK6.log  &


nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20161LogisticRegressionForLK > ~/log/20170502yfq20151LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151NaiveBayesForLK > ~/log/20170502yfq20151NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151DecisionTreeRegressionForLK > ~/log/20170502yfq20151DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151GradientBoostingRegressionForLK341 3 4 > ~/log/20170502yfq20151GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151GradientBoostingRegressionForLK66 6 6 > ~/log/20170502yfq20151GradientBoostingRegressionForLK66.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151GradientBoostingRegressionForLK106 10 6 > ~/log/20170502yfq20151GradientBoostingRegressionForLK106.log   &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151GradientBoostingRegressionForLK941 9 4 > ~/log/20170502yfq20151GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2015_train_variable 20170502yfq20151RandomForestRegressionForLK6 > ~/log/20170502yfq20151RandomForestRegressionForLK6.log  &


nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20161LogisticRegressionForLK > ~/log/20170502yfq20141LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141NaiveBayesForLK > ~/log/20170502yfq20141NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141DecisionTreeRegressionForLK > ~/log/20170502yfq20141DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141GradientBoostingRegressionForLK341 3 4 > ~/log/20170502yfq20141GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141GradientBoostingRegressionForLK66 6 6 > ~/log/20170502yfq20141GradientBoostingRegressionForLK66.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141GradientBoostingRegressionForLK106 10 6 > ~/log/20170502yfq20141GradientBoostingRegressionForLK106.log   &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141GradientBoostingRegressionForLK941 9 4 > ~/log/20170502yfq20141GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_2014_train_variable 20170502yfq20141RandomForestRegressionForLK6 > ~/log/20170502yfq20141RandomForestRegressionForLK6.log  &

--=====================================================================================


nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1LogisticRegressionForLK > ~/log/20170502creditcardrepaymentsnew1LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1NaiveBayesForLK > ~/log/20170502creditcardrepaymentsnew1NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1DecisionTreeRegressionForLK > ~/log/20170502creditcardrepaymentsnew1DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK345 3 4 > ~/log/20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK345.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK385 3 8 > ~/log/20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK385.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK645 6 4 > ~/log/20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK645.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK665 6 6 > ~/log/20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK665.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK945 9 4 > ~/log/20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK945.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK995 9 9 > ~/log/20170502creditcardrepaymentsnew1GradientBoostingRegressionForLK995.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_creditcardrepayments_train_new 20170502creditcardrepaymentsnew1RandomForestRegressionForLK6 > ~/log/20170502creditcardrepaymentsnew1RandomForestRegressionForLK6.log  &


nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1LogisticRegressionForLK > ~/log/20170502enquirybalance1LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1NaiveBayesForLK > ~/log/20170502enquirybalance1NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1DecisionTreeRegressionForLK > ~/log/20170502enquirybalance1DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1GradientBoostingRegressionForLK341 3 4 > ~/log/20170502enquirybalance1GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1GradientBoostingRegressionForLK381 3 8 > ~/log/20170502enquirybalance1GradientBoostingRegressionForLK381.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1GradientBoostingRegressionForLK641 6 4 > ~/log/20170502enquirybalance1GradientBoostingRegressionForLK641.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1GradientBoostingRegressionForLK661 6 6 > ~/log/20170502enquirybalance1GradientBoostingRegressionForLK661.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1GradientBoostingRegressionForLK941 9 4 > ~/log/20170502enquirybalance1GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1GradientBoostingRegressionForLK991 9 9 > ~/log/20170502enquirybalance1GradientBoostingRegressionForLK991.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_enquirybalance_train_new 20170502enquirybalance1RandomForestRegressionForLK6 > ~/log/20170502enquirybalance1RandomForestRegressionForLK6.log  &

nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1LogisticRegressionForLK > ~/log/20170502mobilephonerecharge1LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1NaiveBayesForLK > ~/log/20170502mobilephonerecharge1NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1DecisionTreeRegressionForLK > ~/log/20170502mobilephonerecharge1DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1GradientBoostingRegressionForLK341 3 4 > ~/log/20170502mobilephonerecharge1GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1GradientBoostingRegressionForLK381 3 8 > ~/log/20170502mobilephonerecharge1GradientBoostingRegressionForLK381.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1GradientBoostingRegressionForLK641 6 4 > ~/log/20170502mobilephonerecharge1GradientBoostingRegressionForLK641.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1GradientBoostingRegressionForLK661 6 6 > ~/log/20170502mobilephonerecharge1GradientBoostingRegressionForLK661.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1GradientBoostingRegressionForLK941 9 4 > ~/log/20170502mobilephonerecharge1GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1GradientBoostingRegressionForLK991 9 9 > ~/log/20170502mobilephonerecharge1GradientBoostingRegressionForLK991.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_mobilephonerecharge_train_new 20170502mobilephonerecharge1RandomForestRegressionForLK6 > ~/log/20170502mobilephonerecharge1RandomForestRegressionForLK6.log  &


nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1LogisticRegressionForLK > ~/log/20170502transfers1LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1NaiveBayesForLK > ~/log/20170502transfers1NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1DecisionTreeRegressionForLK > ~/log/20170502transfers1DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1GradientBoostingRegressionForLK341 3 4 > ~/log/20170502transfers1GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1GradientBoostingRegressionForLK381 3 8 > ~/log/20170502transfers1GradientBoostingRegressionForLK381.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1GradientBoostingRegressionForLK641 6 4 > ~/log/20170502transfers1GradientBoostingRegressionForLK641.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1GradientBoostingRegressionForLK661 6 6 > ~/log/20170502transfers1GradientBoostingRegressionForLK661.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1GradientBoostingRegressionForLK941 9 4 > ~/log/20170502transfers1GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1GradientBoostingRegressionForLK991 9 9 > ~/log/20170502transfers1GradientBoostingRegressionForLK991.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_transfers_train_new 20170502transfers1RandomForestRegressionForLK6 > ~/log/20170502transfers1RandomForestRegressionForLK6.log  &


nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.LogisticRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1LogisticRegressionForLK > ~/log/20170502watergaselectricity1LogisticRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.NaiveBayesForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1NaiveBayesForLK > ~/log/20170502watergaselectricity1NaiveBayesForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.DecisionTreeRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1DecisionTreeRegressionForLK > ~/log/20170502watergaselectricity1DecisionTreeRegressionForLK.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1GradientBoostingRegressionForLK341 3 4 > ~/log/20170502watergaselectricity1GradientBoostingRegressionForLK341.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1GradientBoostingRegressionForLK66 6 6 > ~/log/20170502watergaselectricity1GradientBoostingRegressionForLK66.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1GradientBoostingRegressionForLK106 10 6 > ~/log/20170502watergaselectricity1GradientBoostingRegressionForLK106.log   &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.GradientBoostingRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1GradientBoostingRegressionForLK941 9 4 > ~/log/20170502watergaselectricity1GradientBoostingRegressionForLK941.log  &
nohup ./spark-submit --master spark://datacenter17:7077,datacenter18:7077 --conf spark.locality.wait=1 --conf spark.driver.memory=1g  --conf spark.executor.cores=4 --total-executor-cores 8 --num-executors 2 --executor-memory 4g --class lakala.models.RandomForestRegressionForLK /home/hadoop/spark-tools-1.0.jar lkl_card_score phone_variable_yfq_water_gas_electricity_train_new 20170502watergaselectricity1RandomForestRegressionForLK6 > ~/log/20170502watergaselectricity1RandomForestRegressionForLK6.log  &


--L卡分群，时间分群
--======================================================================
--易分期 手机号 流水号 按交易时间年份分群 （2016--2012）
--易分期产品客户全量交易流水 按交易时间分群
--==============================================
--交易流水 按年份时间取最大值 
create table trade_flow_phone_yfq_time as 
select phone,max(substr(endtime,1,4)) as occurrence_time
from  
where buscode not in ('credit','authentication','enquiryFee','financialTransaction')
group by phone;
  
select occurrence_time,count(phone) from trade_flow_phone_yfq_time 
group by occurrence_time ;
 
--======================================================================================= 

--时间分群数据
create table phone_variable_yfq_2016 as 
select b.* from trade_flow_phone_yfq_time a
join phone_variable_yfq  b on a.phone = b.phone
where a.occurrence_time = '2016';

create table phone_variable_yfq_2015 as 
select b.* from trade_flow_phone_yfq_time a
join phone_variable_yfq  b on a.phone = b.phone
where a.occurrence_time = '2015';

create table phone_variable_yfq_2014 as 
select b.* from trade_flow_phone_yfq_time a
join phone_variable_yfq  b on a.phone = b.phone
where a.occurrence_time = '2014';

create table phone_variable_yfq_2013 as 
select b.* from trade_flow_phone_yfq_time a
join phone_variable_yfq  b on a.phone = b.phone
where a.occurrence_time = '2013';

--====================================================================================
--样本数据
create table phone_variable_yfq_2016_train as 
select b.gbie as label,
p.*
 from lkl_card_score_phone_user_yfq t 
join lkl_card_score_credit_contract b on t.contract_no = b.contract_no
join phone_variable_yfq_2016 p on p.phone = lfp.md5(t.mobile)
where b.gbie <> 0.5
and b.type ='yfq'; 

create table phone_variable_yfq_2015_train as 
select b.gbie as label,
p.*
 from lkl_card_score_phone_user_yfq t 
join lkl_card_score_credit_contract b on t.contract_no = b.contract_no
join phone_variable_yfq_2015 p on p.phone = lfp.md5(t.mobile)
where b.gbie <> 0.5
and b.type ='yfq'; 

create table phone_variable_yfq_2014_train as 
select b.gbie as label,
p.*
 from lkl_card_score_phone_user_yfq t 
join lkl_card_score_credit_contract b on t.contract_no = b.contract_no
join phone_variable_yfq_2014 p on p.phone = lfp.md5(t.mobile)
where b.gbie <> 0.5
and b.type ='yfq';  

create table phone_variable_yfq_2013_train as 
select b.gbie as label,
p.*
 from lkl_card_score_phone_user_yfq t 
join lkl_card_score_credit_contract b on t.contract_no = b.contract_no
join phone_variable_yfq_2013 p on p.phone = lfp.md5(t.mobile)
where b.gbie <> 0.5
and b.type ='yfq'; 
--============================================================================================================
--业务分布
select count(1),'0' as val, '2016_train' as type from phone_variable_yfq_2016_train where label = 0
union all
select count(1),'1' as val, '2016_train' as type from phone_variable_yfq_2016_train where label = 1
union all
select count(1),'0' as val, '2015_train' as type from phone_variable_yfq_2015_train where label = 0
union all
select count(1),'1' as val, '2015_train' as type from phone_variable_yfq_2015_train where label = 1
union all
select count(1),'0' as val, '2014_train' as type from phone_variable_yfq_2014_train where label = 0
union all
select count(1),'1' as val, '2014_train' as type from phone_variable_yfq_2014_train where label = 1
union all
select count(1),'0' as val, '2013_train' as type from phone_variable_yfq_2013_train where label = 0
union all
select count(1),'1' as val, '2013_train' as type from phone_variable_yfq_2013_train where label = 1;
--=============================================================================================================


create table phone_variable_yfq_2016_train_variable as 
select 
label,
phone,
sum_amount1_transfers                   ,
avg_amount1_transfers                   ,
max_amount1_transfers                   ,
min_amount1_transfers                   ,
sum_cnt1_transfers                      ,
sum_amount1_financialtransaction        ,
avg_amount1_financialtransaction        ,
max_amount1_financialtransaction        ,
min_amount1_financialtransaction        ,
sum_cnt1_financialtransaction           ,
sum_amount2_transfers                   ,
avg_amount2_transfers                   ,
max_amount2_transfers                   ,
min_amount2_transfers                   ,
sum_cnt2_transfers                      ,
sum_amount1_mobilephonerecharge         ,
avg_amount1_mobilephonerecharge         ,
max_amount1_mobilephonerecharge         ,
min_amount1_mobilephonerecharge         ,
sum_cnt1_mobilephonerecharge            ,
sum_amount28_mobilephonerecharge        ,
avg_amount28_mobilephonerecharge        ,
max_amount28_mobilephonerecharge        ,
min_amount28_mobilephonerecharge        ,
sum_cnt28_mobilephonerecharge           ,
sum_amount22_mobilephonerecharge        ,
avg_amount22_mobilephonerecharge        ,
max_amount22_mobilephonerecharge        ,
min_amount22_mobilephonerecharge        ,
sum_cnt22_mobilephonerecharge           ,
sum_amount23_mobilephonerecharge        ,
avg_amount23_mobilephonerecharge        ,
max_amount23_mobilephonerecharge        ,
min_amount23_mobilephonerecharge        ,
sum_cnt23_mobilephonerecharge           ,
sum_amount27_mobilephonerecharge        ,
avg_amount27_mobilephonerecharge        ,
max_amount27_mobilephonerecharge        ,
min_amount27_mobilephonerecharge        ,
sum_cnt27_mobilephonerecharge           ,
sum_amount24_mobilephonerecharge        ,
avg_amount24_mobilephonerecharge        ,
max_amount24_mobilephonerecharge        ,
min_amount24_mobilephonerecharge        ,
sum_cnt24_mobilephonerecharge           ,
sum_amount19_mobilephonerecharge        ,
avg_amount19_mobilephonerecharge        ,
max_amount19_mobilephonerecharge        ,
min_amount19_mobilephonerecharge        ,
sum_cnt19_mobilephonerecharge           ,
sum_amount26_mobilephonerecharge        ,
avg_amount26_mobilephonerecharge        ,
max_amount26_mobilephonerecharge        ,
min_amount26_mobilephonerecharge        ,
sum_cnt26_mobilephonerecharge           ,
sum_amount18_mobilephonerecharge        ,
avg_amount18_mobilephonerecharge        ,
max_amount18_mobilephonerecharge        ,
min_amount18_mobilephonerecharge        ,
sum_cnt18_mobilephonerecharge           ,
sum_amount25_mobilephonerecharge        ,
avg_amount25_mobilephonerecharge        ,
max_amount25_mobilephonerecharge        ,
min_amount25_mobilephonerecharge        ,
sum_cnt25_mobilephonerecharge           ,
sum_amount20_mobilephonerecharge        ,
avg_amount20_mobilephonerecharge        ,
max_amount20_mobilephonerecharge        ,
min_amount20_mobilephonerecharge        ,
sum_cnt20_mobilephonerecharge           ,
sum_amount21_mobilephonerecharge        ,
avg_amount21_mobilephonerecharge        ,
max_amount21_mobilephonerecharge        ,
min_amount21_mobilephonerecharge        ,
sum_cnt21_mobilephonerecharge           ,
sum_amount30_mobilephonerecharge        ,
avg_amount30_mobilephonerecharge        ,
max_amount30_mobilephonerecharge        ,
min_amount30_mobilephonerecharge        ,
sum_cnt30_mobilephonerecharge           ,
sum_amount29_mobilephonerecharge        ,
avg_amount29_mobilephonerecharge        ,
max_amount29_mobilephonerecharge        ,
min_amount29_mobilephonerecharge        ,
sum_cnt29_mobilephonerecharge           ,
sum_amount31_mobilephonerecharge        ,
avg_amount31_mobilephonerecharge        ,
max_amount31_mobilephonerecharge        ,
min_amount31_mobilephonerecharge        ,
sum_cnt31_mobilephonerecharge           ,
sum_amount3_transfers                   ,
avg_amount3_transfers                   ,
max_amount3_transfers                   ,
min_amount3_transfers                   ,
sum_cnt3_transfers                      ,
sum_amount17_mobilephonerecharge        ,
avg_amount17_mobilephonerecharge        ,
max_amount17_mobilephonerecharge        ,
min_amount17_mobilephonerecharge        ,
sum_cnt17_mobilephonerecharge           ,
sum_amount16_mobilephonerecharge        ,
avg_amount16_mobilephonerecharge        ,
max_amount16_mobilephonerecharge        ,
min_amount16_mobilephonerecharge        ,
sum_cnt16_mobilephonerecharge           ,
sum_amount32_mobilephonerecharge        ,
avg_amount32_mobilephonerecharge        ,
max_amount32_mobilephonerecharge        ,
min_amount32_mobilephonerecharge        ,
sum_cnt32_mobilephonerecharge           ,
sum_amount15_mobilephonerecharge        ,
avg_amount15_mobilephonerecharge        ,
max_amount15_mobilephonerecharge        ,
min_amount15_mobilephonerecharge        ,
sum_cnt15_mobilephonerecharge           ,
sum_amount4_transfers                   ,
avg_amount4_transfers                   ,
max_amount4_transfers                   ,
min_amount4_transfers                   ,
sum_cnt4_transfers                      ,
sum_amount14_mobilephonerecharge        ,
avg_amount14_mobilephonerecharge        ,
max_amount14_mobilephonerecharge        ,
min_amount14_mobilephonerecharge        ,
sum_cnt14_mobilephonerecharge           ,
sum_amount33_mobilephonerecharge        ,
avg_amount33_mobilephonerecharge        ,
max_amount33_mobilephonerecharge        ,
min_amount33_mobilephonerecharge        ,
sum_cnt33_mobilephonerecharge           ,
sum_amount13_mobilephonerecharge        ,
avg_amount13_mobilephonerecharge        ,
max_amount13_mobilephonerecharge        ,
min_amount13_mobilephonerecharge        ,
sum_cnt13_mobilephonerecharge           ,
sum_amount2_financialtransaction        ,
avg_amount2_financialtransaction        ,
max_amount2_financialtransaction        ,
min_amount2_financialtransaction        ,
sum_cnt2_financialtransaction           ,
sum_amount34_mobilephonerecharge        ,
avg_amount34_mobilephonerecharge        ,
max_amount34_mobilephonerecharge        ,
min_amount34_mobilephonerecharge        ,
sum_cnt34_mobilephonerecharge           ,
sum_amount12_mobilephonerecharge        ,
avg_amount12_mobilephonerecharge        ,
max_amount12_mobilephonerecharge        ,
min_amount12_mobilephonerecharge        ,
sum_cnt12_mobilephonerecharge           ,
sum_amount11_mobilephonerecharge        ,
avg_amount11_mobilephonerecharge        ,
max_amount11_mobilephonerecharge        ,
min_amount11_mobilephonerecharge        ,
sum_cnt11_mobilephonerecharge           ,
sum_amount10_mobilephonerecharge        ,
avg_amount10_mobilephonerecharge        ,
max_amount10_mobilephonerecharge        ,
min_amount10_mobilephonerecharge        ,
sum_cnt10_mobilephonerecharge           ,
sum_amount1_enquirybalance              ,
avg_amount1_enquirybalance              ,
max_amount1_enquirybalance              ,
min_amount1_enquirybalance              ,
sum_cnt1_enquirybalance                 ,
sum_amount35_mobilephonerecharge        ,
avg_amount35_mobilephonerecharge        ,
max_amount35_mobilephonerecharge        ,
min_amount35_mobilephonerecharge        ,
sum_cnt35_mobilephonerecharge           ,
sum_amount5_transfers                   ,
avg_amount5_transfers                   ,
max_amount5_transfers                   ,
min_amount5_transfers                   ,
sum_cnt5_transfers                      ,
sum_amount9_mobilephonerecharge         ,
avg_amount9_mobilephonerecharge         ,
max_amount9_mobilephonerecharge         ,
min_amount9_mobilephonerecharge         ,
sum_cnt9_mobilephonerecharge            ,
sum_amount36_mobilephonerecharge        ,
avg_amount36_mobilephonerecharge        ,
max_amount36_mobilephonerecharge        ,
min_amount36_mobilephonerecharge        ,
sum_cnt36_mobilephonerecharge           ,
sum_amount6_transfers                   ,
avg_amount6_transfers                   ,
max_amount6_transfers                   ,
min_amount6_transfers                   ,
sum_cnt6_transfers                      ,
sum_amount7_transfers                   ,
avg_amount7_transfers                   ,
max_amount7_transfers                   ,
min_amount7_transfers                   ,
sum_cnt7_transfers                      ,
sum_amount2_mobilephonerecharge         ,
avg_amount2_mobilephonerecharge         ,
max_amount2_mobilephonerecharge         ,
min_amount2_mobilephonerecharge         ,
sum_cnt2_mobilephonerecharge            ,
sum_amount3_financialtransaction        ,
avg_amount3_financialtransaction        ,
max_amount3_financialtransaction        ,
min_amount3_financialtransaction        ,
sum_cnt3_financialtransaction           ,
sum_amount8_mobilephonerecharge         ,
avg_amount8_mobilephonerecharge         ,
max_amount8_mobilephonerecharge         ,
min_amount8_mobilephonerecharge         ,
sum_cnt8_mobilephonerecharge            ,
sum_amount8_transfers                   ,
avg_amount8_transfers                   ,
max_amount8_transfers                   ,
min_amount8_transfers                   ,
sum_cnt8_transfers                      ,
sum_amount6_mobilephonerecharge         ,
avg_amount6_mobilephonerecharge         ,
max_amount6_mobilephonerecharge         ,
min_amount6_mobilephonerecharge         ,
sum_cnt6_mobilephonerecharge            ,
sum_amount7_mobilephonerecharge         ,
avg_amount7_mobilephonerecharge         ,
max_amount7_mobilephonerecharge         ,
min_amount7_mobilephonerecharge         ,
sum_cnt7_mobilephonerecharge            ,
sum_amount37_mobilephonerecharge        ,
avg_amount37_mobilephonerecharge        ,
max_amount37_mobilephonerecharge        ,
min_amount37_mobilephonerecharge        ,
sum_cnt37_mobilephonerecharge           ,
sum_amount2_enquirybalance              ,
avg_amount2_enquirybalance              ,
max_amount2_enquirybalance              ,
min_amount2_enquirybalance              ,
sum_cnt2_enquirybalance                 ,
sum_amount38_mobilephonerecharge        ,
avg_amount38_mobilephonerecharge        ,
max_amount38_mobilephonerecharge        ,
min_amount38_mobilephonerecharge        ,
sum_cnt38_mobilephonerecharge           ,
sum_amount9_transfers                   ,
avg_amount9_transfers                   ,
max_amount9_transfers                   ,
min_amount9_transfers                   ,
sum_cnt9_transfers                      ,
sum_amount39_mobilephonerecharge        ,
avg_amount39_mobilephonerecharge        ,
max_amount39_mobilephonerecharge        ,
min_amount39_mobilephonerecharge        ,
sum_cnt39_mobilephonerecharge           ,
sum_amount10_transfers                  ,
avg_amount10_transfers                  ,
max_amount10_transfers                  ,
min_amount10_transfers                  ,
sum_cnt10_transfers                     ,
sum_amount4_mobilephonerecharge         ,
avg_amount4_mobilephonerecharge         ,
max_amount4_mobilephonerecharge         ,
min_amount4_mobilephonerecharge         ,
sum_cnt4_mobilephonerecharge            ,
sum_amount3_enquirybalance              ,
avg_amount3_enquirybalance              ,
max_amount3_enquirybalance              ,
min_amount3_enquirybalance              ,
sum_cnt3_enquirybalance                 ,
sum_amount3_mobilephonerecharge         ,
avg_amount3_mobilephonerecharge         ,
max_amount3_mobilephonerecharge         ,
min_amount3_mobilephonerecharge         ,
sum_cnt3_mobilephonerecharge            ,
sum_amount5_mobilephonerecharge         ,
avg_amount5_mobilephonerecharge         ,
max_amount5_mobilephonerecharge         ,
min_amount5_mobilephonerecharge         ,
sum_cnt5_mobilephonerecharge            ,
sum_amount8_enquirybalance              ,
avg_amount8_enquirybalance              ,
max_amount8_enquirybalance              ,
min_amount8_enquirybalance              ,
sum_cnt8_enquirybalance                 ,
sum_amount9_enquirybalance              ,
avg_amount9_enquirybalance              ,
max_amount9_enquirybalance              ,
min_amount9_enquirybalance              ,
sum_cnt9_enquirybalance                 ,
sum_amount4_enquirybalance              ,
avg_amount4_enquirybalance              ,
max_amount4_enquirybalance              ,
min_amount4_enquirybalance              ,
sum_cnt4_enquirybalance                 ,
sum_amount12_enquirybalance             ,
avg_amount12_enquirybalance             ,
max_amount12_enquirybalance             ,
min_amount12_enquirybalance             ,
sum_cnt12_enquirybalance                ,
sum_amount11_transfers                  ,
avg_amount11_transfers                  ,
max_amount11_transfers                  ,
min_amount11_transfers                  ,
sum_cnt11_transfers                     ,
sum_amount12_transfers                  ,
avg_amount12_transfers                  ,
max_amount12_transfers                  ,
min_amount12_transfers                  ,
sum_cnt12_transfers                     ,
sum_amount10_enquirybalance             ,
avg_amount10_enquirybalance             ,
max_amount10_enquirybalance             ,
min_amount10_enquirybalance             ,
sum_cnt10_enquirybalance                ,
sum_amount7_enquirybalance              ,
avg_amount7_enquirybalance              ,
max_amount7_enquirybalance              ,
min_amount7_enquirybalance              ,
sum_cnt7_enquirybalance                 ,
sum_amount4_financialtransaction        ,
avg_amount4_financialtransaction        ,
max_amount4_financialtransaction        ,
min_amount4_financialtransaction        ,
sum_cnt4_financialtransaction           ,
sum_amount40_mobilephonerecharge        ,
avg_amount40_mobilephonerecharge        ,
max_amount40_mobilephonerecharge        ,
min_amount40_mobilephonerecharge        ,
sum_cnt40_mobilephonerecharge           ,
sum_amount6_enquirybalance              ,
avg_amount6_enquirybalance              ,
max_amount6_enquirybalance              ,
min_amount6_enquirybalance              ,
sum_cnt6_enquirybalance                 ,
sum_amount5_enquirybalance              ,
avg_amount5_enquirybalance              ,
max_amount5_enquirybalance              ,
min_amount5_enquirybalance              ,
sum_cnt5_enquirybalance                 ,
sum_amount11_enquirybalance             ,
avg_amount11_enquirybalance             ,
max_amount11_enquirybalance             ,
min_amount11_enquirybalance             ,
sum_cnt11_enquirybalance                ,
sum_amount14_enquirybalance             ,
avg_amount14_enquirybalance             ,
max_amount14_enquirybalance             ,
min_amount14_enquirybalance             ,
sum_cnt14_enquirybalance                ,
sum_amount15_enquirybalance             ,
avg_amount15_enquirybalance             ,
max_amount15_enquirybalance             ,
min_amount15_enquirybalance             ,
sum_cnt15_enquirybalance                ,
sum_amount41_mobilephonerecharge        ,
avg_amount41_mobilephonerecharge        ,
max_amount41_mobilephonerecharge        ,
min_amount41_mobilephonerecharge        ,
sum_cnt41_mobilephonerecharge           ,
sum_amount13_enquirybalance             ,
avg_amount13_enquirybalance             ,
max_amount13_enquirybalance             ,
min_amount13_enquirybalance             ,
sum_cnt13_enquirybalance                ,
sum_amount13_transfers                  ,
avg_amount13_transfers                  ,
max_amount13_transfers                  ,
min_amount13_transfers                  ,
sum_cnt13_transfers                     ,
sum_amount15_transfers                  ,
avg_amount15_transfers                  ,
max_amount15_transfers                  ,
min_amount15_transfers                  ,
sum_cnt15_transfers                     ,
sum_amount16_enquirybalance             ,
avg_amount16_enquirybalance             ,
max_amount16_enquirybalance             ,
min_amount16_enquirybalance             ,
sum_cnt16_enquirybalance                ,
sum_amount14_transfers                  ,
avg_amount14_transfers                  ,
max_amount14_transfers                  ,
min_amount14_transfers                  ,
sum_cnt14_transfers                     ,
sum_amount17_enquirybalance             ,
avg_amount17_enquirybalance             ,
max_amount17_enquirybalance             ,
min_amount17_enquirybalance             ,
sum_cnt17_enquirybalance                ,
sum_amount16_transfers                  ,
avg_amount16_transfers                  ,
max_amount16_transfers                  ,
min_amount16_transfers                  ,
sum_cnt16_transfers                     ,
sum_amount42_mobilephonerecharge        ,
avg_amount42_mobilephonerecharge        ,
max_amount42_mobilephonerecharge        ,
min_amount42_mobilephonerecharge        ,
sum_cnt42_mobilephonerecharge           ,
sum_amount18_enquirybalance             ,
avg_amount18_enquirybalance             ,
max_amount18_enquirybalance             ,
min_amount18_enquirybalance             ,
sum_cnt18_enquirybalance                ,
sum_amount17_transfers                  ,
avg_amount17_transfers                  ,
max_amount17_transfers                  ,
min_amount17_transfers                  ,
sum_cnt17_transfers                     ,
sum_amount19_enquirybalance             ,
avg_amount19_enquirybalance             ,
max_amount19_enquirybalance             ,
min_amount19_enquirybalance             ,
sum_cnt19_enquirybalance                ,
sum_amount21_enquirybalance             ,
avg_amount21_enquirybalance             ,
max_amount21_enquirybalance             ,
min_amount21_enquirybalance             ,
sum_cnt21_enquirybalance                ,
sum_amount18_transfers                  ,
avg_amount18_transfers                  ,
max_amount18_transfers                  ,
min_amount18_transfers                  ,
sum_cnt18_transfers                     ,
sum_amount21_transfers                  ,
avg_amount21_transfers                  ,
max_amount21_transfers                  ,
min_amount21_transfers                  ,
sum_cnt21_transfers                     
from phone_variable_yfq_2016_train;



--========================================================================================

create table phone_variable_yfq_2015_train_variable as 
select
label,
phone, 
sum_amount24_mobilephonerecharge		,
avg_amount24_mobilephonerecharge        ,
max_amount24_mobilephonerecharge        ,
min_amount24_mobilephonerecharge        ,
sum_cnt24_mobilephonerecharge           ,
sum_amount25_mobilephonerecharge        ,
avg_amount25_mobilephonerecharge        ,
max_amount25_mobilephonerecharge        ,
min_amount25_mobilephonerecharge        ,
sum_cnt25_mobilephonerecharge           ,
sum_amount26_mobilephonerecharge        ,
avg_amount26_mobilephonerecharge        ,
max_amount26_mobilephonerecharge        ,
min_amount26_mobilephonerecharge        ,
sum_cnt26_mobilephonerecharge           ,
sum_amount23_mobilephonerecharge        ,
avg_amount23_mobilephonerecharge        ,
max_amount23_mobilephonerecharge        ,
min_amount23_mobilephonerecharge        ,
sum_cnt23_mobilephonerecharge           ,
sum_amount22_mobilephonerecharge        ,
avg_amount22_mobilephonerecharge        ,
max_amount22_mobilephonerecharge        ,
min_amount22_mobilephonerecharge        ,
sum_cnt22_mobilephonerecharge           ,
sum_amount28_mobilephonerecharge        ,
avg_amount28_mobilephonerecharge        ,
max_amount28_mobilephonerecharge        ,
min_amount28_mobilephonerecharge        ,
sum_cnt28_mobilephonerecharge           ,
sum_amount27_mobilephonerecharge        ,
avg_amount27_mobilephonerecharge        ,
max_amount27_mobilephonerecharge        ,
min_amount27_mobilephonerecharge        ,
sum_cnt27_mobilephonerecharge           ,
sum_amount20_mobilephonerecharge        ,
avg_amount20_mobilephonerecharge        ,
max_amount20_mobilephonerecharge        ,
min_amount20_mobilephonerecharge        ,
sum_cnt20_mobilephonerecharge           ,
sum_amount18_mobilephonerecharge        ,
avg_amount18_mobilephonerecharge        ,
max_amount18_mobilephonerecharge        ,
min_amount18_mobilephonerecharge        ,
sum_cnt18_mobilephonerecharge           ,
sum_amount21_mobilephonerecharge        ,
avg_amount21_mobilephonerecharge        ,
max_amount21_mobilephonerecharge        ,
min_amount21_mobilephonerecharge        ,
sum_cnt21_mobilephonerecharge           ,
sum_amount19_mobilephonerecharge        ,
avg_amount19_mobilephonerecharge        ,
max_amount19_mobilephonerecharge        ,
min_amount19_mobilephonerecharge        ,
sum_cnt19_mobilephonerecharge           ,
sum_amount17_mobilephonerecharge        ,
avg_amount17_mobilephonerecharge        ,
max_amount17_mobilephonerecharge        ,
min_amount17_mobilephonerecharge        ,
sum_cnt17_mobilephonerecharge           ,
sum_amount29_mobilephonerecharge        ,
avg_amount29_mobilephonerecharge        ,
max_amount29_mobilephonerecharge        ,
min_amount29_mobilephonerecharge        ,
sum_cnt29_mobilephonerecharge           ,
sum_amount16_mobilephonerecharge        ,
avg_amount16_mobilephonerecharge        ,
max_amount16_mobilephonerecharge        ,
min_amount16_mobilephonerecharge        ,
sum_cnt16_mobilephonerecharge           ,
sum_amount15_mobilephonerecharge        ,
avg_amount15_mobilephonerecharge        ,
max_amount15_mobilephonerecharge        ,
min_amount15_mobilephonerecharge        ,
sum_cnt15_mobilephonerecharge           ,
sum_amount30_mobilephonerecharge        ,
avg_amount30_mobilephonerecharge        ,
max_amount30_mobilephonerecharge        ,
min_amount30_mobilephonerecharge        ,
sum_cnt30_mobilephonerecharge           ,
sum_amount14_mobilephonerecharge        ,
avg_amount14_mobilephonerecharge        ,
max_amount14_mobilephonerecharge        ,
min_amount14_mobilephonerecharge        ,
sum_cnt14_mobilephonerecharge           ,
sum_amount31_mobilephonerecharge        ,
avg_amount31_mobilephonerecharge        ,
max_amount31_mobilephonerecharge        ,
min_amount31_mobilephonerecharge        ,
sum_cnt31_mobilephonerecharge           ,
sum_amount13_mobilephonerecharge        ,
avg_amount13_mobilephonerecharge        ,
max_amount13_mobilephonerecharge        ,
min_amount13_mobilephonerecharge        ,
sum_cnt13_mobilephonerecharge           ,
sum_amount32_mobilephonerecharge        ,
avg_amount32_mobilephonerecharge        ,
max_amount32_mobilephonerecharge        ,
min_amount32_mobilephonerecharge        ,
sum_cnt32_mobilephonerecharge           ,
sum_amount12_mobilephonerecharge        ,
avg_amount12_mobilephonerecharge        ,
max_amount12_mobilephonerecharge        ,
min_amount12_mobilephonerecharge        ,
sum_cnt12_mobilephonerecharge           ,
sum_amount33_mobilephonerecharge        ,
avg_amount33_mobilephonerecharge        ,
max_amount33_mobilephonerecharge        ,
min_amount33_mobilephonerecharge        ,
sum_cnt33_mobilephonerecharge           ,
sum_amount11_mobilephonerecharge        ,
avg_amount11_mobilephonerecharge        ,
max_amount11_mobilephonerecharge        ,
min_amount11_mobilephonerecharge        ,
sum_cnt11_mobilephonerecharge           ,
sum_amount34_mobilephonerecharge        ,
avg_amount34_mobilephonerecharge        ,
max_amount34_mobilephonerecharge        ,
min_amount34_mobilephonerecharge        ,
sum_cnt34_mobilephonerecharge           ,
sum_amount10_mobilephonerecharge        ,
avg_amount10_mobilephonerecharge        ,
max_amount10_mobilephonerecharge        ,
min_amount10_mobilephonerecharge        ,
sum_cnt10_mobilephonerecharge           ,
sum_amount35_mobilephonerecharge        ,
avg_amount35_mobilephonerecharge        ,
max_amount35_mobilephonerecharge        ,
min_amount35_mobilephonerecharge        ,
sum_cnt35_mobilephonerecharge           ,
sum_amount9_mobilephonerecharge         ,
avg_amount9_mobilephonerecharge         ,
max_amount9_mobilephonerecharge         ,
min_amount9_mobilephonerecharge         ,
sum_cnt9_mobilephonerecharge            ,
sum_amount11_enquirybalance             ,
avg_amount11_enquirybalance             ,
max_amount11_enquirybalance             ,
min_amount11_enquirybalance             ,
sum_cnt11_enquirybalance                ,
sum_amount10_enquirybalance             ,
avg_amount10_enquirybalance             ,
max_amount10_enquirybalance             ,
min_amount10_enquirybalance             ,
sum_cnt10_enquirybalance                ,
sum_amount11_transfers                  ,
avg_amount11_transfers                  ,
max_amount11_transfers                  ,
min_amount11_transfers                  ,
sum_cnt11_transfers                     ,
sum_amount36_mobilephonerecharge        ,
avg_amount36_mobilephonerecharge        ,
max_amount36_mobilephonerecharge        ,
min_amount36_mobilephonerecharge        ,
sum_cnt36_mobilephonerecharge           ,
sum_amount8_mobilephonerecharge         ,
avg_amount8_mobilephonerecharge         ,
max_amount8_mobilephonerecharge         ,
min_amount8_mobilephonerecharge         ,
sum_cnt8_mobilephonerecharge            ,
sum_amount7_transfers                   ,
avg_amount7_transfers                   ,
max_amount7_transfers                   ,
min_amount7_transfers                   ,
sum_cnt7_transfers                      ,
sum_amount8_transfers                   ,
avg_amount8_transfers                   ,
max_amount8_transfers                   ,
min_amount8_transfers                   ,
sum_cnt8_transfers                      ,
sum_amount9_enquirybalance              ,
avg_amount9_enquirybalance              ,
max_amount9_enquirybalance              ,
min_amount9_enquirybalance              ,
sum_cnt9_enquirybalance                 ,
sum_amount8_enquirybalance              ,
avg_amount8_enquirybalance              ,
max_amount8_enquirybalance              ,
min_amount8_enquirybalance              ,
sum_cnt8_enquirybalance                 ,
sum_amount12_enquirybalance             ,
avg_amount12_enquirybalance             ,
max_amount12_enquirybalance             ,
min_amount12_enquirybalance             ,
sum_cnt12_enquirybalance                ,
sum_amount14_enquirybalance             ,
avg_amount14_enquirybalance             ,
max_amount14_enquirybalance             ,
min_amount14_enquirybalance             ,
sum_cnt14_enquirybalance                ,
sum_amount10_transfers                  ,
avg_amount10_transfers                  ,
max_amount10_transfers                  ,
min_amount10_transfers                  ,
sum_cnt10_transfers                     ,
sum_amount6_transfers                   ,
avg_amount6_transfers                   ,
max_amount6_transfers                   ,
min_amount6_transfers                   ,
sum_cnt6_transfers                      ,
sum_amount9_transfers                   ,
avg_amount9_transfers                   ,
max_amount9_transfers                   ,
min_amount9_transfers                   ,
sum_cnt9_transfers                      ,
sum_amount15_enquirybalance             ,
avg_amount15_enquirybalance             ,
max_amount15_enquirybalance             ,
min_amount15_enquirybalance             ,
sum_cnt15_enquirybalance                ,
sum_amount7_enquirybalance              ,
avg_amount7_enquirybalance              ,
max_amount7_enquirybalance              ,
min_amount7_enquirybalance              ,
sum_cnt7_enquirybalance                 ,
sum_amount5_transfers                   ,
avg_amount5_transfers                   ,
max_amount5_transfers                   ,
min_amount5_transfers                   ,
sum_cnt5_transfers                      ,
sum_amount7_mobilephonerecharge         ,
avg_amount7_mobilephonerecharge         ,
max_amount7_mobilephonerecharge         ,
min_amount7_mobilephonerecharge         ,
sum_cnt7_mobilephonerecharge            ,
sum_amount17_enquirybalance             ,
avg_amount17_enquirybalance             ,
max_amount17_enquirybalance             ,
min_amount17_enquirybalance             ,
sum_cnt17_enquirybalance                ,
sum_amount15_transfers                  ,
avg_amount15_transfers                  ,
max_amount15_transfers                  ,
min_amount15_transfers                  ,
sum_cnt15_transfers                     ,
sum_amount13_enquirybalance             ,
avg_amount13_enquirybalance             ,
max_amount13_enquirybalance             ,
min_amount13_enquirybalance             ,
sum_cnt13_enquirybalance                ,
sum_amount17_transfers                  ,
avg_amount17_transfers                  ,
max_amount17_transfers                  ,
min_amount17_transfers                  ,
sum_cnt17_transfers                     ,
sum_amount14_transfers                  ,
avg_amount14_transfers                  ,
max_amount14_transfers                  ,
min_amount14_transfers                  ,
sum_cnt14_transfers                     ,
sum_amount6_enquirybalance              ,
avg_amount6_enquirybalance              ,
max_amount6_enquirybalance              ,
min_amount6_enquirybalance              ,
sum_cnt6_enquirybalance                 ,
sum_amount12_transfers                  ,
avg_amount12_transfers                  ,
max_amount12_transfers                  ,
min_amount12_transfers                  ,
sum_cnt12_transfers                     ,
sum_amount16_enquirybalance             ,
avg_amount16_enquirybalance             ,
max_amount16_enquirybalance             ,
min_amount16_enquirybalance             ,
sum_cnt16_enquirybalance                ,
sum_amount13_transfers                  ,
avg_amount13_transfers                  ,
max_amount13_transfers                  ,
min_amount13_transfers                  ,
sum_cnt13_transfers                     ,
sum_amount4_transfers                   ,
avg_amount4_transfers                   ,
max_amount4_transfers                   ,
min_amount4_transfers                   ,
sum_cnt4_transfers                      ,
sum_amount20_transfers                  ,
avg_amount20_transfers                  ,
max_amount20_transfers                  ,
min_amount20_transfers                  ,
sum_cnt20_transfers                     ,
sum_amount16_transfers                  ,
avg_amount16_transfers                  ,
max_amount16_transfers                  ,
min_amount16_transfers                  ,
sum_cnt16_transfers                     ,
sum_amount20_enquirybalance             ,
avg_amount20_enquirybalance             ,
max_amount20_enquirybalance             ,
min_amount20_enquirybalance             ,
sum_cnt20_enquirybalance                ,
sum_amount37_mobilephonerecharge        ,
avg_amount37_mobilephonerecharge        ,
max_amount37_mobilephonerecharge        ,
min_amount37_mobilephonerecharge        ,
sum_cnt37_mobilephonerecharge           ,
sum_amount18_enquirybalance             ,
avg_amount18_enquirybalance             ,
max_amount18_enquirybalance             ,
min_amount18_enquirybalance             ,
sum_cnt18_enquirybalance                ,
sum_amount18_transfers                  ,
avg_amount18_transfers                  ,
max_amount18_transfers                  ,
min_amount18_transfers                  ,
sum_cnt18_transfers                     ,
sum_amount5_enquirybalance              ,
avg_amount5_enquirybalance              ,
max_amount5_enquirybalance              ,
min_amount5_enquirybalance              ,
sum_cnt5_enquirybalance                 ,
sum_amount19_transfers                  ,
avg_amount19_transfers                  ,
max_amount19_transfers                  ,
min_amount19_transfers                  ,
sum_cnt19_transfers                     ,
sum_amount19_enquirybalance             ,
avg_amount19_enquirybalance             ,
max_amount19_enquirybalance             ,
min_amount19_enquirybalance             ,
sum_cnt19_enquirybalance                ,
sum_amount21_transfers                  ,
avg_amount21_transfers                  ,
max_amount21_transfers                  ,
min_amount21_transfers                  ,
sum_cnt21_transfers                     ,
sum_amount22_transfers                  ,
avg_amount22_transfers                  ,
max_amount22_transfers                  ,
min_amount22_transfers                  ,
sum_cnt22_transfers                     ,
sum_amount38_mobilephonerecharge        ,
avg_amount38_mobilephonerecharge        ,
max_amount38_mobilephonerecharge        ,
min_amount38_mobilephonerecharge        ,
sum_cnt38_mobilephonerecharge           ,
sum_amount6_mobilephonerecharge         ,
avg_amount6_mobilephonerecharge         ,
max_amount6_mobilephonerecharge         ,
min_amount6_mobilephonerecharge         ,
sum_cnt6_mobilephonerecharge            ,
sum_amount22_enquirybalance             ,
avg_amount22_enquirybalance             ,
max_amount22_enquirybalance             ,
min_amount22_enquirybalance             ,
sum_cnt22_enquirybalance                ,
sum_amount21_enquirybalance             ,
avg_amount21_enquirybalance             ,
max_amount21_enquirybalance             ,
min_amount21_enquirybalance             ,
sum_cnt21_enquirybalance                ,
sum_amount4_enquirybalance              ,
avg_amount4_enquirybalance              ,
max_amount4_enquirybalance              ,
min_amount4_enquirybalance              ,
sum_cnt4_enquirybalance                 ,
sum_amount3_transfers                   ,
avg_amount3_transfers                   ,
max_amount3_transfers                   ,
min_amount3_transfers                   ,
sum_cnt3_transfers                      ,
sum_amount39_mobilephonerecharge        ,
avg_amount39_mobilephonerecharge        ,
max_amount39_mobilephonerecharge        ,
min_amount39_mobilephonerecharge        ,
sum_cnt39_mobilephonerecharge           ,
sum_amount5_mobilephonerecharge         ,
avg_amount5_mobilephonerecharge         ,
max_amount5_mobilephonerecharge         ,
min_amount5_mobilephonerecharge         ,
sum_cnt5_mobilephonerecharge            ,
sum_amount23_transfers                  ,
avg_amount23_transfers                  ,
max_amount23_transfers                  ,
min_amount23_transfers                  ,
sum_cnt23_transfers                     ,
sum_amount24_transfers                  ,
avg_amount24_transfers                  ,
max_amount24_transfers                  ,
min_amount24_transfers                  ,
sum_cnt24_transfers                     ,
sum_amount23_enquirybalance             ,
avg_amount23_enquirybalance             ,
max_amount23_enquirybalance             ,
min_amount23_enquirybalance             ,
sum_cnt23_enquirybalance                ,
sum_amount2_transfers                   ,
avg_amount2_transfers                   ,
max_amount2_transfers                   ,
min_amount2_transfers                   ,
sum_cnt2_transfers                      ,
sum_amount25_transfers                  ,
avg_amount25_transfers                  ,
max_amount25_transfers                  ,
min_amount25_transfers                  ,
sum_cnt25_transfers                     ,
sum_amount24_enquirybalance             ,
avg_amount24_enquirybalance             ,
max_amount24_enquirybalance             ,
min_amount24_enquirybalance             ,
sum_cnt24_enquirybalance                ,
sum_amount25_enquirybalance             ,
avg_amount25_enquirybalance             ,
max_amount25_enquirybalance             ,
min_amount25_enquirybalance             ,
sum_cnt25_enquirybalance                ,
sum_amount1_transfers                   ,
avg_amount1_transfers                   ,
max_amount1_transfers                   ,
min_amount1_transfers                   ,
sum_cnt1_transfers                      ,
sum_amount26_transfers                  ,
avg_amount26_transfers                  ,
max_amount26_transfers                  ,
min_amount26_transfers                  ,
sum_cnt26_transfers                     ,
sum_amount4_mobilephonerecharge         ,
avg_amount4_mobilephonerecharge         ,
max_amount4_mobilephonerecharge         ,
min_amount4_mobilephonerecharge         ,
sum_cnt4_mobilephonerecharge            ,
sum_amount3_enquirybalance              ,
avg_amount3_enquirybalance              ,
max_amount3_enquirybalance              ,
min_amount3_enquirybalance              ,
sum_cnt3_enquirybalance                 ,
sum_amount26_enquirybalance             ,
avg_amount26_enquirybalance             ,
max_amount26_enquirybalance             ,
min_amount26_enquirybalance             ,
sum_cnt26_enquirybalance                ,
sum_amount27_enquirybalance             ,
avg_amount27_enquirybalance             ,
max_amount27_enquirybalance             ,
min_amount27_enquirybalance             ,
sum_cnt27_enquirybalance                ,
sum_amount40_mobilephonerecharge        ,
avg_amount40_mobilephonerecharge        ,
max_amount40_mobilephonerecharge        ,
min_amount40_mobilephonerecharge        ,
sum_cnt40_mobilephonerecharge           ,
sum_amount27_transfers                  ,
avg_amount27_transfers                  ,
max_amount27_transfers                  ,
min_amount27_transfers                  ,
sum_cnt27_transfers                     ,
sum_amount2_enquirybalance              ,
avg_amount2_enquirybalance              ,
max_amount2_enquirybalance              ,
min_amount2_enquirybalance              ,
sum_cnt2_enquirybalance                 ,
sum_amount28_transfers                  ,
avg_amount28_transfers                  ,
max_amount28_transfers                  ,
min_amount28_transfers                  ,
sum_cnt28_transfers                     ,
sum_amount3_mobilephonerecharge         ,
avg_amount3_mobilephonerecharge         ,
max_amount3_mobilephonerecharge         ,
min_amount3_mobilephonerecharge         ,
sum_cnt3_mobilephonerecharge            ,
sum_amount1_enquirybalance              ,
avg_amount1_enquirybalance              ,
max_amount1_enquirybalance              ,
min_amount1_enquirybalance              ,
sum_cnt1_enquirybalance                 ,
sum_amount28_enquirybalance             ,
avg_amount28_enquirybalance             ,
max_amount28_enquirybalance             ,
min_amount28_enquirybalance             ,
sum_cnt28_enquirybalance                ,
sum_amount41_mobilephonerecharge        ,
avg_amount41_mobilephonerecharge        ,
max_amount41_mobilephonerecharge        ,
min_amount41_mobilephonerecharge        ,
sum_cnt41_mobilephonerecharge           ,
sum_amount1_financialtransaction        ,
avg_amount1_financialtransaction        ,
max_amount1_financialtransaction        ,
min_amount1_financialtransaction        ,
sum_cnt1_financialtransaction           ,
sum_amount2_mobilephonerecharge         ,
avg_amount2_mobilephonerecharge         ,
max_amount2_mobilephonerecharge         ,
min_amount2_mobilephonerecharge         ,
sum_cnt2_mobilephonerecharge            ,
sum_amount29_transfers                  ,
avg_amount29_transfers                  ,
max_amount29_transfers                  ,
min_amount29_transfers                  ,
sum_cnt29_transfers                     ,
sum_amount29_enquirybalance             ,
avg_amount29_enquirybalance             ,
max_amount29_enquirybalance             ,
min_amount29_enquirybalance             ,
sum_cnt29_enquirybalance                ,
sum_amount1_mobilephonerecharge         ,
avg_amount1_mobilephonerecharge         ,
max_amount1_mobilephonerecharge         ,
min_amount1_mobilephonerecharge         ,
sum_cnt1_mobilephonerecharge            ,
sum_amount42_mobilephonerecharge        ,
avg_amount42_mobilephonerecharge        ,
max_amount42_mobilephonerecharge        ,
min_amount42_mobilephonerecharge        ,
sum_cnt42_mobilephonerecharge           ,
sum_amount12_acquiring                  ,
avg_amount12_acquiring                  ,
max_amount12_acquiring                  ,
min_amount12_acquiring                  ,
sum_cnt12_acquiring                     ,
sum_amount30_enquirybalance             ,
avg_amount30_enquirybalance             ,
max_amount30_enquirybalance             ,
min_amount30_enquirybalance             ,
sum_cnt30_enquirybalance                ,
sum_amount13_acquiring                  ,
avg_amount13_acquiring                  ,
max_amount13_acquiring                  ,
min_amount13_acquiring                  ,
sum_cnt13_acquiring                     ,
sum_amount30_transfers                  ,
avg_amount30_transfers                  ,
max_amount30_transfers                  ,
min_amount30_transfers                  ,
sum_cnt30_transfers                     ,
sum_amount11_acquiring                  ,
avg_amount11_acquiring                  ,
max_amount11_acquiring                  ,
min_amount11_acquiring                  ,
sum_cnt11_acquiring                     ,
sum_amount14_acquiring                  ,
avg_amount14_acquiring                  ,
max_amount14_acquiring                  ,
min_amount14_acquiring                  ,
sum_cnt14_acquiring                     ,
sum_amount15_acquiring                  ,
avg_amount15_acquiring                  ,
max_amount15_acquiring                  ,
min_amount15_acquiring                  ,
sum_cnt15_acquiring                     ,
sum_amount43_mobilephonerecharge        ,
avg_amount43_mobilephonerecharge        ,
max_amount43_mobilephonerecharge        ,
min_amount43_mobilephonerecharge        ,
sum_cnt43_mobilephonerecharge           ,
sum_amount16_acquiring                  ,
avg_amount16_acquiring                  ,
max_amount16_acquiring                  ,
min_amount16_acquiring                  ,
sum_cnt16_acquiring                     ,
sum_amount31_enquirybalance             ,
avg_amount31_enquirybalance             ,
max_amount31_enquirybalance             ,
min_amount31_enquirybalance             ,
sum_cnt31_enquirybalance                ,
sum_amount10_acquiring                  ,
avg_amount10_acquiring                  ,
max_amount10_acquiring                  ,
min_amount10_acquiring                  ,
sum_cnt10_acquiring                     ,
sum_amount31_transfers                  ,
avg_amount31_transfers                  ,
max_amount31_transfers                  ,
min_amount31_transfers                  ,
sum_cnt31_transfers                     ,
sum_amount17_acquiring                  ,
avg_amount17_acquiring                  ,
max_amount17_acquiring                  ,
min_amount17_acquiring                  ,
sum_cnt17_acquiring                     ,
sum_amount18_acquiring                  ,
avg_amount18_acquiring                  ,
max_amount18_acquiring                  ,
min_amount18_acquiring                  ,
sum_cnt18_acquiring                     ,
sum_amount2_financialtransaction        ,
avg_amount2_financialtransaction        ,
max_amount2_financialtransaction        ,
min_amount2_financialtransaction        ,
sum_cnt2_financialtransaction           ,
sum_amount32_enquirybalance             ,
avg_amount32_enquirybalance             ,
max_amount32_enquirybalance             ,
min_amount32_enquirybalance             ,
sum_cnt32_enquirybalance                ,
sum_amount19_acquiring                  ,
avg_amount19_acquiring                  ,
max_amount19_acquiring                  ,
min_amount19_acquiring                  ,
sum_cnt19_acquiring                     ,
sum_amount32_transfers                  ,
avg_amount32_transfers                  ,
max_amount32_transfers                  ,
min_amount32_transfers                  ,
sum_cnt32_transfers                     ,
sum_amount9_acquiring                   ,
avg_amount9_acquiring                   ,
max_amount9_acquiring                   ,
min_amount9_acquiring                   ,
sum_cnt9_acquiring                      ,
sum_amount44_mobilephonerecharge        ,
avg_amount44_mobilephonerecharge        ,
max_amount44_mobilephonerecharge        ,
min_amount44_mobilephonerecharge        ,
sum_cnt44_mobilephonerecharge           ,
sum_amount4_financialtransaction        ,
avg_amount4_financialtransaction        ,
max_amount4_financialtransaction        ,
min_amount4_financialtransaction        ,
sum_cnt4_financialtransaction           ,
sum_amount5_financialtransaction        ,
avg_amount5_financialtransaction        ,
max_amount5_financialtransaction        ,
min_amount5_financialtransaction        ,
sum_cnt5_financialtransaction           ,
sum_amount3_financialtransaction        ,
avg_amount3_financialtransaction        ,
max_amount3_financialtransaction        ,
min_amount3_financialtransaction        ,
sum_cnt3_financialtransaction           ,
sum_amount8_acquiring                   ,
avg_amount8_acquiring                   ,
max_amount8_acquiring                   ,
min_amount8_acquiring                   ,
sum_cnt8_acquiring                      ,
sum_amount33_enquirybalance             ,
avg_amount33_enquirybalance             ,
max_amount33_enquirybalance             ,
min_amount33_enquirybalance             ,
sum_cnt33_enquirybalance                ,
sum_amount33_transfers                  ,
avg_amount33_transfers                  ,
max_amount33_transfers                  ,
min_amount33_transfers                  ,
sum_cnt33_transfers                     ,
sum_amount20_acquiring                  ,
avg_amount20_acquiring                  ,
max_amount20_acquiring                  ,
min_amount20_acquiring                  ,
sum_cnt20_acquiring                     ,
sum_amount6_financialtransaction        ,
avg_amount6_financialtransaction        ,
max_amount6_financialtransaction        ,
min_amount6_financialtransaction        ,
sum_cnt6_financialtransaction           ,
sum_amount7_acquiring                   ,
avg_amount7_acquiring                   ,
max_amount7_acquiring                   ,
min_amount7_acquiring                   ,
sum_cnt7_acquiring                      ,
sum_amount7_financialtransaction        ,
avg_amount7_financialtransaction        ,
max_amount7_financialtransaction        ,
min_amount7_financialtransaction        ,
sum_cnt7_financialtransaction           ,
sum_amount45_mobilephonerecharge        ,
avg_amount45_mobilephonerecharge        ,
max_amount45_mobilephonerecharge        ,
min_amount45_mobilephonerecharge        ,
sum_cnt45_mobilephonerecharge           ,
sum_amount34_enquirybalance             ,
avg_amount34_enquirybalance             ,
max_amount34_enquirybalance             ,
min_amount34_enquirybalance             ,
sum_cnt34_enquirybalance                ,
sum_amount34_transfers                  ,
avg_amount34_transfers                  ,
max_amount34_transfers                  ,
min_amount34_transfers                  ,
sum_cnt34_transfers                     ,
sum_amount21_acquiring                  ,
avg_amount21_acquiring                  ,
max_amount21_acquiring                  ,
min_amount21_acquiring                  ,
sum_cnt21_acquiring                     ,
sum_amount22_acquiring                  ,
avg_amount22_acquiring                  ,
max_amount22_acquiring                  ,
min_amount22_acquiring                  ,
sum_cnt22_acquiring                     ,
sum_amount35_enquirybalance             ,
avg_amount35_enquirybalance             ,
max_amount35_enquirybalance             ,
min_amount35_enquirybalance             ,
sum_cnt35_enquirybalance                
from phone_variable_yfq_2015_train;




--================================================================

create table phone_variable_yfq_2014_train_variable as 
select 
label,
phone,
sum_amount28_mobilephonerecharge         ,     
avg_amount28_mobilephonerecharge         ,
max_amount28_mobilephonerecharge         ,
min_amount28_mobilephonerecharge         ,
sum_cnt28_mobilephonerecharge            ,
sum_amount29_mobilephonerecharge         ,
avg_amount29_mobilephonerecharge         ,
max_amount29_mobilephonerecharge         ,
min_amount29_mobilephonerecharge         ,
sum_cnt29_mobilephonerecharge            ,
sum_amount27_mobilephonerecharge         ,
avg_amount27_mobilephonerecharge         ,
max_amount27_mobilephonerecharge         ,
min_amount27_mobilephonerecharge         ,
sum_cnt27_mobilephonerecharge            ,
sum_amount30_mobilephonerecharge         ,
avg_amount30_mobilephonerecharge         ,
max_amount30_mobilephonerecharge         ,
min_amount30_mobilephonerecharge         ,
sum_cnt30_mobilephonerecharge            ,
sum_amount26_mobilephonerecharge         ,
avg_amount26_mobilephonerecharge         ,
max_amount26_mobilephonerecharge         ,
min_amount26_mobilephonerecharge         ,
sum_cnt26_mobilephonerecharge            ,
sum_amount25_mobilephonerecharge         ,
avg_amount25_mobilephonerecharge         ,
max_amount25_mobilephonerecharge         ,
min_amount25_mobilephonerecharge         ,
sum_cnt25_mobilephonerecharge            ,
sum_amount32_mobilephonerecharge         ,
avg_amount32_mobilephonerecharge         ,
max_amount32_mobilephonerecharge         ,
min_amount32_mobilephonerecharge         ,
sum_cnt32_mobilephonerecharge            ,
sum_amount31_mobilephonerecharge         ,
avg_amount31_mobilephonerecharge         ,
max_amount31_mobilephonerecharge         ,
min_amount31_mobilephonerecharge         ,
sum_cnt31_mobilephonerecharge            ,
sum_amount33_mobilephonerecharge         ,
avg_amount33_mobilephonerecharge         ,
max_amount33_mobilephonerecharge         ,
min_amount33_mobilephonerecharge         ,
sum_cnt33_mobilephonerecharge            ,
sum_amount24_mobilephonerecharge         ,
avg_amount24_mobilephonerecharge         ,
max_amount24_mobilephonerecharge         ,
min_amount24_mobilephonerecharge         ,
sum_cnt24_mobilephonerecharge            ,
sum_amount34_mobilephonerecharge         ,
avg_amount34_mobilephonerecharge         ,
max_amount34_mobilephonerecharge         ,
min_amount34_mobilephonerecharge         ,
sum_cnt34_mobilephonerecharge            ,
sum_amount23_mobilephonerecharge         ,
avg_amount23_mobilephonerecharge         ,
max_amount23_mobilephonerecharge         ,
min_amount23_mobilephonerecharge         ,
sum_cnt23_mobilephonerecharge            ,
sum_amount35_mobilephonerecharge         ,
avg_amount35_mobilephonerecharge         ,
max_amount35_mobilephonerecharge         ,
min_amount35_mobilephonerecharge         ,
sum_cnt35_mobilephonerecharge            ,
sum_amount36_mobilephonerecharge         ,
avg_amount36_mobilephonerecharge         ,
max_amount36_mobilephonerecharge         ,
min_amount36_mobilephonerecharge         ,
sum_cnt36_mobilephonerecharge            ,
sum_amount22_mobilephonerecharge         ,
avg_amount22_mobilephonerecharge         ,
max_amount22_mobilephonerecharge         ,
min_amount22_mobilephonerecharge         ,
sum_cnt22_mobilephonerecharge            ,
sum_amount37_mobilephonerecharge         ,
avg_amount37_mobilephonerecharge         ,
max_amount37_mobilephonerecharge         ,
min_amount37_mobilephonerecharge         ,
sum_cnt37_mobilephonerecharge            ,
sum_amount38_mobilephonerecharge         ,
avg_amount38_mobilephonerecharge         ,
max_amount38_mobilephonerecharge         ,
min_amount38_mobilephonerecharge         ,
sum_cnt38_mobilephonerecharge            ,
sum_amount20_mobilephonerecharge         ,
avg_amount20_mobilephonerecharge         ,
max_amount20_mobilephonerecharge         ,
min_amount20_mobilephonerecharge         ,
sum_cnt20_mobilephonerecharge            ,
sum_amount39_mobilephonerecharge         ,
avg_amount39_mobilephonerecharge         ,
max_amount39_mobilephonerecharge         ,
min_amount39_mobilephonerecharge         ,
sum_cnt39_mobilephonerecharge            ,
sum_amount21_mobilephonerecharge         ,
avg_amount21_mobilephonerecharge         ,
max_amount21_mobilephonerecharge         ,
min_amount21_mobilephonerecharge         ,
sum_cnt21_mobilephonerecharge            ,
sum_amount22_enquirybalance              ,
avg_amount22_enquirybalance              ,
max_amount22_enquirybalance              ,
min_amount22_enquirybalance              ,
sum_cnt22_enquirybalance                 ,
sum_amount40_mobilephonerecharge         ,
avg_amount40_mobilephonerecharge         ,
max_amount40_mobilephonerecharge         ,
min_amount40_mobilephonerecharge         ,
sum_cnt40_mobilephonerecharge            ,
sum_amount26_transfers                   ,
avg_amount26_transfers                   ,
max_amount26_transfers                   ,
min_amount26_transfers                   ,
sum_cnt26_transfers                      ,
sum_amount24_transfers                   ,
avg_amount24_transfers                   ,
max_amount24_transfers                   ,
min_amount24_transfers                   ,
sum_cnt24_transfers                      ,
sum_amount25_transfers                   ,
avg_amount25_transfers                   ,
max_amount25_transfers                   ,
min_amount25_transfers                   ,
sum_cnt25_transfers                      ,
sum_amount25_enquirybalance              ,
avg_amount25_enquirybalance              ,
max_amount25_enquirybalance              ,
min_amount25_enquirybalance              ,
sum_cnt25_enquirybalance                 ,
sum_amount26_enquirybalance              ,
avg_amount26_enquirybalance              ,
max_amount26_enquirybalance              ,
min_amount26_enquirybalance              ,
sum_cnt26_enquirybalance                 ,
sum_amount22_transfers                   ,
avg_amount22_transfers                   ,
max_amount22_transfers                   ,
min_amount22_transfers                   ,
sum_cnt22_transfers                      ,
sum_amount24_enquirybalance              ,
avg_amount24_enquirybalance              ,
max_amount24_enquirybalance              ,
min_amount24_enquirybalance              ,
sum_cnt24_enquirybalance                 ,
sum_amount27_enquirybalance              ,
avg_amount27_enquirybalance              ,
max_amount27_enquirybalance              ,
min_amount27_enquirybalance              ,
sum_cnt27_enquirybalance                 ,
sum_amount23_transfers                   ,
avg_amount23_transfers                   ,
max_amount23_transfers                   ,
min_amount23_transfers                   ,
sum_cnt23_transfers                      ,
sum_amount27_transfers                   ,
avg_amount27_transfers                   ,
max_amount27_transfers                   ,
min_amount27_transfers                   ,
sum_cnt27_transfers                      ,
sum_amount23_enquirybalance              ,
avg_amount23_enquirybalance              ,
max_amount23_enquirybalance              ,
min_amount23_enquirybalance              ,
sum_cnt23_enquirybalance                 
from phone_variable_yfq_2014_train;



